### ISSUE TITLE
Add support of Rider

### ISSUE THREAD

**Issue by laurentkempe** [github/codespaces-jetbrains-feedback#5]
I cannot work on my C# projects using GitHub Codespaces as I cannot see Rider listed on JetBrains Gateway
![image](https://user-images.githubusercontent.com/272612/200917219-fb3c1c1b-6483-46c4-9240-5734354fe6be.png)

**Comment by shayneburgess** [comment]
We are actively working on Rider support. Stay tuned

**Comment by askpt** [comment]
Cannot wait to start using Rider. As much as I like VSCode, it doesn't have the same level of debugging and tools that Rider has!

**Comment by iAmBipinPaul** [comment]
Hi @shayneburgess any ETA?

**Comment by cmuto09** [comment]
Hi @iAmBipinPaul- we do not have an estimate just yet, but when we do I will update the thread. Thanks!

**Comment by mscottford** [comment]
I'm not sure if I've done anything wrong or not, but I'm still not seeing Rider in the list for "Select IDE". 

JetBrains toolbox version: `JetBrains Toolbox 1.27.1.13673, macOS 13.0.1`
JetBrains Gateway version info:
```
JetBrains Gateway 2022.3
Build #GW-223.7571.203, built on November 30, 2022
Runtime version: 17.0.5+1-b653.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    com.github.codespaces.jetbrains.gateway (0.3.0.971)
```

**Comment by cmuto09** [comment]
Hmm... those versions look correct. @trent-j @thomas-sickert any ideas as to what might be happening?

**Comment by thomas-sickert** [comment]
Just double checking--did you made sure to enable the Rider preview in the Codespaces preferences page on the Gateway?

Other than that, those configurations you have look correct to me.

**Comment by mscottford** [comment]
That magical checkbox! :)

Screenshot in case it helps others. I'm guessing this only shows up after I've set the Java property via the JVM options file.
![Screenshot 2022-12-08 at 8 39 34 AM](https://user-images.githubusercontent.com/21340/206461098-dbf3bda5-4f64-4d1b-94f1-17fc63e0ef2c.png)

Although, while it is showing Rider in the list now, it's giving preference to the now expired EAP over the complete 2020.3 release. I can try to uninstall the EAP and see what that does.

![Screenshot 2022-12-08 at 8 41 51 AM](https://user-images.githubusercontent.com/21340/206461397-ff4b5cb2-7034-41cc-b8d1-abb4a8706d7c.png)

Please wait while I try that. ;) I thought of it I was typing this out.

(What follows is a line-by-line log of what I did, and what I encountered along the way. Hopefully, it's helpful and not annoying.)

Strange. I uninstalled the EAP via JetBrains Toolbox, but the EAP version still appears in the list. 

It let me connect and then gave me an error about sshd not being installed as a feature. I added it and then tried again.

After connecting, I saw an error message about the "new UI" setting being enabled and that the client and server needed to be restarted, because of that. 

Rider launched taking up all of the screen real-estate (not sure if that's a Gateway issue or not). On my ultra-wide screen monitor, that was a bit much.

There is a warning message that "the recommended heap size for a machine this size is 8192 MiB but the current setting is 2048 MiB. Performance may be degraded It is recommended to increase the heap size. (I'm connecting to a 16-core codespace.) 

I'm clicking "Update heap size and restart IDE". That gave me an "Unable to update vmoptions file" error message. Again, not sure if this is an issue with the plugin or just a Gateway quirk.

**Comment by thomas-sickert** [comment]
Glad you got it working! Thanks for all of this info.

Rider is still in EAP for remote dev. We'll have a release version at some point, but it's out of band of the others at the moment. 

The new UI setting setting might have something to do with the EAP tag, but I'm not sure. I've also seen that error message intermittently. I've turned off the new UI for now and I don't see the warning anymore.

I'm curious, does resizing the Rider client after the first launch makes subsequent launches default to that size?

That heap size fix is a bug that we're in the process of fixing now. I'm hoping to get a change out in the immediate future, but if you need to adjust the heap size you can do so from the backend settings panel in the top left (to see it, you may need to enable the navigation bar in the menus--View → Appearance → Navigation Bar) or by going to Help → Edit Custom VM Options... (On Host) and then updating the `-Xmx1500m` value to be the reflect the memory you'd like. 

Thanks again for the feedback!

**Comment by cmuto09** [comment]
Hi all! We are very excited to announce that Rider is now available through the Codespaces plugin in the JetBrains Gateway! Upgrading to the latest plugin version will enable Rider for use.

Check out our [change log post](https://github.blog/changelog/2023-02-24-codespaces-support-for-jetbrains-rider-beta/) for additional information about the release.

Thank you all for the feedback, and excited to hear what you think!

Closing this issue as Rider is now supported 🚀
